# version: '3.8' 

# services:
#   app:
#     build: .
#     ports:
#       - "5000:80"
#     environment:
#       - MongoDBSettings__ConnectionString=mongodb://mongo:27017
#     depends_on:
#       - mongo

#   mongo:
#     image: mongo:4.2
#     ports:
#       - "27017:27017"
#     volumes:
#       - mongo-data:/data/db

# volumes:
#   mongo-data:
